### ISSUE TITLE
page not found when accepting license (because of #36)?

### ISSUE THREAD

**Issue by Apollo3zehn** [nexus-main/nexus#65]

**Comment by Conundraah** [comment]
I think the issue is resolved and may be closed. After the following steps

- commenting out lines 158 - 159 (firstUser is not automatically administrator) in /src/Nexus/Core/NexusAuthExtensions.cs
- adding a license to the catalogBuilder (catalogBuilder.WithLicense("Test license")) in Sample.cs, line 246
- commenting out lines 76 - 78 (sample catalogs are not automatically readable) in /src/Nexus/Utilities/AuthUtilities.cs
- deleting users.db and all cookies in browser

The first user sees the following on index.razor:
![Select Root Catalog](https://github.com/user-attachments/assets/36b66bcc-df3c-4804-9e65-29b999e3c054)

After selecting the root catalog:
![Select Local With License](https://github.com/user-attachments/assets/d0e2818a-74a8-49d6-bbf4-c9147c94e134)

After accepting the license:
![Select Local after accepting license](https://github.com/user-attachments/assets/7d4d5312-dc70-4db7-a989-7eec01321ea7)

Maybe resolving #36 in a previous issue really already solved the issue described here.

**Comment by Apollo3zehn** [comment]
Thank you!
